export const Users = [
    {
      id:1,
      profilePicture: "/assets/img/friends/1.jpg",
      username: "Mr.Pilkington",
    },
    {
      id:2,
      profilePicture: "/assets/img/friends/2.jpg",
      username: "Zar",
    },
    {
      id:3,
      profilePicture: "/assets/img/friends/3.jpg",
      username: "Nikolai",
    },
    {
      id:4,
      profilePicture: "/assets/img/friends/4.jpg",
      username: "Manolo",
    },
    {
      id:5,
      profilePicture: "/assets/img/friends/5.jpg",
      username: "karem",
    },
    {
      id:6,
      profilePicture: "/assets/img/friends/6.jpg",
      username: "otto",
    },
    {
      id:7,
      profilePicture: "/assets/img/friends/7.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "/assets/img/friends/8.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "/assets/img/friends/9.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "/assets/img/friends/10.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Primer meme",
      photo: "/assets/img/post/1.jpg",
      date: "hace 5 min",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/assets/img/post/2.jpg",
      date: "hace 15 min",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "/assets/img/post/3.jpg",
      date: "hace 1 hora",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "/assets/img/post/4.jpg",
      date: "hace 4 horas",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "/assets/img/post/5.jpg",
      date: "hace 5 horas",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "/assets/img/post/6.jpg",
      date: "hace 1 dia",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "/assets/img/post/7.jpg",
      date: "hace 2 dias",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "/assets/img/post/8.jpg",
      date: "hace 3 dias",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "/assets/img/post/9.jpg",
      date: "hace 5 dias",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "/assets/img/post/11.jpg",
      date: "hace 1 mes",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];